import { NextRequest } from 'next/server'
import { jsonError, jsonStoredSuccess, jsonSuccess, successBody } from '@/lib/api/response'
import { getMockStore, getMutation, mutationKey, saveMutation } from '@/lib/mock-store'
import { mutationMeta, paginationParams, paginated, parseObject, requiredString, optionalString, requireSpace, spaceMismatch, validFileSources, validPriorities } from '@/lib/knowledge-api'
import { FilePriority, FileSource, type KnowledgeFile, type KnowledgeFileType } from '@/lib/types/knowledge'
export const dynamic = 'force-dynamic'
const validTypes = ['markdown', 'pdf', 'code', 'note', 'conversation'] as const

export async function GET(request: NextRequest) {
  const params = new URL(request.url).searchParams
  const spaceId = optionalString({ value: params.get('spaceId') }, 'value', 100); const priority = params.get('priority'); const tags = (params.get('tag') ?? params.get('tags'))?.split(',').map((tag) => tag.trim()).filter(Boolean); const folderId = params.get('folderId'); const sort = params.get('sort') ?? 'smart'; const badSpace = requireSpace(request, spaceId); if (badSpace) return badSpace
  if (priority && !validPriorities.includes(priority as FilePriority)) return jsonError(request, 400, 'INVALID_QUERY', 'priority 不是有效值', false, { priority }); if (!['smart', 'recent', 'priority', 'title', 'updatedAt'].includes(sort)) return jsonError(request, 400, 'INVALID_QUERY', 'sort 不是有效值', false, { sort })
  const pagination = paginationParams(request); if ('error' in pagination) return pagination.error
  const order: Record<string, number> = { critical: 0, pending: 1, normal: 2 }; const now = Date.now(); const files = getMockStore().knowledgeFiles.filter((file) => (!spaceId || file.spaceId === spaceId) && (!priority || file.priority === priority) && (!tags || tags.some((tag) => file.tags.includes(tag))) && (!folderId || file.folderId === folderId))
  files.sort((a, b) => { if (sort === 'priority') return order[a.priority] - order[b.priority]; if (sort === 'title') return a.title.localeCompare(b.title); if (sort === 'recent' || sort === 'updatedAt') return b.lastAccessedAt.localeCompare(a.lastAccessedAt); const score = (file: typeof a) => -order[file.priority] * 50 + (file.aiSummary?.status === 'completed' ? 20 : 0) + Math.max(0, 7 - (now - Date.parse(file.lastAccessedAt)) / 86400000) * 10; return score(b) - score(a) })
  return jsonSuccess(request, paginated(files, pagination.page, pagination.limit))
}

export async function POST(request: NextRequest) {
  const parsed = await parseObject(request); if (parsed.error) return parsed.error; const body = parsed.value!; const title = requiredString(body, 'title', 200); const content = typeof body.content === 'string' ? body.content : undefined; const spaceId = requiredString(body, 'spaceId', 100); const type = body.type ?? 'markdown'; const source = body.source ?? FileSource.MANUAL_UPLOAD; const priority = body.priority ?? FilePriority.NORMAL; const tags = Array.isArray(body.tags) && body.tags.every((tag) => typeof tag === 'string') ? body.tags as string[] : []
  if (!title || content === undefined || !spaceId || !validTypes.includes(type as typeof validTypes[number]) || !validFileSources.includes(source as FileSource) || !validPriorities.includes(priority as FilePriority) || content.length > 10 * 1024 * 1024) return jsonError(request, 400, 'INVALID_REQUEST', 'title、content、spaceId 或文件字段无效', false)
  const spaceError = requireSpace(request, spaceId); if (spaceError) return spaceError; const folderId = optionalString(body, 'folderId', 100); if (folderId) { const folder = getMockStore().knowledgeFolders.find((item) => item.id === folderId); if (!folder) return jsonError(request, 404, 'FOLDER_NOT_FOUND', '文件夹不存在', false, { folderId }); const mismatch = spaceMismatch(request, spaceId, folder.spaceId); if (mismatch) return mismatch }
  const meta = mutationMeta(body); const store = getMockStore(); const key = mutationKey(`knowledge-files:create:${meta.actor}`, meta.clientMutationId); const previous = getMutation(store, key); if (previous) return jsonStoredSuccess(previous.body, previous.status); const now = new Date().toISOString(); const file: KnowledgeFile = { id: `kfile-${crypto.randomUUID()}`, spaceId, folderId, title, type: type as KnowledgeFileType, source: source as FileSource, priority: priority as FilePriority, starred: false, tags, content, metadata: { size: `${content.length} B`, author: typeof body.author === 'string' ? body.author : meta.actor, relatedConversationId: optionalString(body, 'relatedConversationId', 100) }, verified: false, accessCount: 0, createdAt: now, updatedAt: now, lastAccessedAt: now }; store.knowledgeFiles.push(file); const response = successBody(request, file, { status: 201 }); saveMutation(store, key, 201, response); return jsonStoredSuccess(response, 201)
}
