import { NextRequest } from 'next/server'
import { jsonError, jsonStoredSuccess, jsonSuccess, successBody } from '@/lib/api/response'
import { getMockStore, getMutation, mutationKey, saveMutation } from '@/lib/mock-store'
import { KnowledgeRouteContext, mutationMeta, optionalString, parseObject, requestedSpaceMismatch, requiredString, requireSpace, spaceMismatch, validPriorities } from '@/lib/knowledge-api'
import { FilePriority, type KnowledgeFile } from '@/lib/types/knowledge'
export const dynamic = 'force-dynamic'; type Ctx = KnowledgeRouteContext<{ id: string }>
function find(id: string) { return getMockStore().knowledgeFiles.find((file) => file.id === id) }
export async function GET(request: NextRequest, context: Ctx) { const { id } = await context.params; const file = find(id); if (!file) return jsonError(request, 404, 'FILE_NOT_FOUND', '知识库文件不存在', false, { id }); const mismatch = requestedSpaceMismatch(request, file.spaceId); return mismatch ?? jsonSuccess(request, file) }
export async function PATCH(request: NextRequest, context: Ctx) {
  const { id } = await context.params; const file = find(id); if (!file) return jsonError(request, 404, 'FILE_NOT_FOUND', '知识库文件不存在', false, { id }); const parsed = await parseObject(request); if (parsed.error) return parsed.error; const body = parsed.value!; const targetSpace = optionalString(body, 'spaceId', 100) ?? file.spaceId; const targetSpaceError = requireSpace(request, targetSpace); if (targetSpaceError) return targetSpaceError; const spaceError = spaceMismatch(request, file.spaceId, body.spaceId as string | undefined); if (spaceError && targetSpace === file.spaceId) return spaceError
  const folderId = body.folderId === null ? undefined : optionalString(body, 'folderId', 100); if (folderId) { const folder = getMockStore().knowledgeFolders.find((item) => item.id === folderId); if (!folder) return jsonError(request, 404, 'FOLDER_NOT_FOUND', '文件夹不存在', false, { folderId }); const mismatch = spaceMismatch(request, targetSpace, folder.spaceId); if (mismatch) return mismatch }
  const priority = body.priority === undefined ? file.priority : body.priority; if (!validPriorities.includes(priority as FilePriority)) return jsonError(request, 400, 'INVALID_REQUEST', 'priority 不是有效值', false)
  const meta = mutationMeta(body); const store = getMockStore(); const key = mutationKey(`knowledge-files:update:${id}:${meta.actor}`, meta.clientMutationId); const previous = getMutation(store, key); if (previous) return jsonStoredSuccess(previous.body, previous.status); const updated: KnowledgeFile = { ...file, spaceId: targetSpace, folderId, title: body.title === undefined ? file.title : requiredString(body, 'title', 200) ?? file.title, tags: Array.isArray(body.tags) && body.tags.every((tag) => typeof tag === 'string') ? body.tags as string[] : file.tags, priority: priority as FilePriority, updatedAt: new Date().toISOString() }; store.knowledgeFiles[store.knowledgeFiles.indexOf(file)] = updated; const response = successBody(request, updated); saveMutation(store, key, 200, response); return jsonStoredSuccess(response, 200)
}
export async function DELETE(request: NextRequest, context: Ctx) { const { id } = await context.params; const store = getMockStore(); const file = find(id); if (!file) return jsonError(request, 404, 'FILE_NOT_FOUND', '知识库文件不存在', false, { id }); store.knowledgeFiles.splice(store.knowledgeFiles.indexOf(file), 1); return jsonSuccess(request, { id, deleted: true }) }
