import { NextRequest } from 'next/server'
import { jsonError, jsonStoredSuccess, jsonSuccess, successBody } from '@/lib/api/response'
import { getMockStore, getMutation, mutationKey, saveMutation } from '@/lib/mock-store'
import { KnowledgeRouteContext, mutationMeta, optionalString, parseObject, requestedSpaceMismatch, requiredString, spaceMismatch } from '@/lib/knowledge-api'
import { ErrorSeverity, ErrorStatus, type ErrorEntry } from '@/lib/types/knowledge'
export const dynamic = 'force-dynamic'; type Ctx = KnowledgeRouteContext<{ id: string }>
function find(id: string) { return getMockStore().knowledgeErrors.find((entry) => entry.id === id) }
export async function GET(request: NextRequest, context: Ctx) { const { id } = await context.params; const entry = find(id); if (!entry) return jsonError(request, 404, 'ERROR_NOT_FOUND', '错题不存在', false, { id }); const mismatch = requestedSpaceMismatch(request, entry.spaceId); return mismatch ?? jsonSuccess(request, entry) }
export async function PATCH(request: NextRequest, context: Ctx) { const { id } = await context.params; const entry = find(id); if (!entry) return jsonError(request, 404, 'ERROR_NOT_FOUND', '错题不存在', false, { id }); const parsed = await parseObject(request); if (parsed.error) return parsed.error; const body = parsed.value!; const mismatch = spaceMismatch(request, entry.spaceId, body.spaceId as string | undefined); if (mismatch) return mismatch; const status = body.status === undefined ? entry.status : body.status; const severity = body.severity === undefined ? entry.severity : body.severity; if (!Object.values(ErrorStatus).includes(status as ErrorStatus) || !Object.values(ErrorSeverity).includes(severity as ErrorSeverity)) return jsonError(request, 400, 'INVALID_REQUEST', 'status 或 severity 无效', false); const meta = mutationMeta(body); const store = getMockStore(); const key = mutationKey(`knowledge-errors:update:${id}:${meta.actor}`, meta.clientMutationId); const previous = getMutation(store, key); if (previous) return jsonStoredSuccess(previous.body, previous.status); const updated: ErrorEntry = { ...entry, title: body.title === undefined ? entry.title : requiredString(body, 'title', 200) ?? entry.title, solution: body.solution === undefined ? entry.solution : optionalString(body, 'solution', 10000), status: status as ErrorStatus, severity: severity as ErrorSeverity, resolvedAt: status === ErrorStatus.RESOLVED ? new Date().toISOString() : entry.resolvedAt, lastOccurredAt: new Date().toISOString() }; store.knowledgeErrors[store.knowledgeErrors.indexOf(entry)] = updated; const response = successBody(request, updated); saveMutation(store, key, 200, response); return jsonStoredSuccess(response, 200) }
