import { NextRequest } from 'next/server'
import { jsonError, jsonStoredSuccess, jsonSuccess, successBody } from '@/lib/api/response'
import { getMockStore, getMutation, mutationKey, saveMutation } from '@/lib/mock-store'
import { KnowledgeRouteContext, mutationMeta, optionalString, parseObject, requiredString } from '@/lib/knowledge-api'
import type { Folder } from '@/lib/types/knowledge'
export const dynamic = 'force-dynamic'; type Ctx = KnowledgeRouteContext<{ id: string }>
function find(id: string) { return getMockStore().knowledgeFolders.find((folder) => folder.id === id) }
export async function PATCH(request: NextRequest, context: Ctx) { const { id } = await context.params; const folder = find(id); if (!folder) return jsonError(request, 404, 'FOLDER_NOT_FOUND', '文件夹不存在', false, { id }); const parsed = await parseObject(request); if (parsed.error) return parsed.error; const body = parsed.value!; const name = body.name === undefined ? folder.name : requiredString(body, 'name', 100); const parentId = body.parentId === null ? undefined : optionalString(body, 'parentId', 100); if (!name) return jsonError(request, 400, 'INVALID_REQUEST', 'name 必须是非空字符串', false); if (parentId === id) return jsonError(request, 400, 'INVALID_REQUEST', '文件夹不能移动到自身', false); if (parentId) { const parent = find(parentId); if (!parent) return jsonError(request, 404, 'FOLDER_NOT_FOUND', '父文件夹不存在', false, { parentId }); if (parent.spaceId !== folder.spaceId) return jsonError(request, 403, 'SPACE_MISMATCH', '父文件夹不属于当前空间', false) } const meta = mutationMeta(body); const store = getMockStore(); const key = mutationKey(`knowledge-folders:update:${id}:${meta.actor}`, meta.clientMutationId); const previous = getMutation(store, key); if (previous) return jsonStoredSuccess(previous.body, previous.status); const updated: Folder = { ...folder, name, parentId, collapsed: body.collapsed === undefined ? folder.collapsed : body.collapsed === true }; store.knowledgeFolders[store.knowledgeFolders.indexOf(folder)] = updated; const response = successBody(request, updated); saveMutation(store, key, 200, response); return jsonStoredSuccess(response, 200) }
export async function DELETE(request: NextRequest, context: Ctx) { const { id } = await context.params; const store = getMockStore(); const folder = find(id); if (!folder) return jsonError(request, 404, 'FOLDER_NOT_FOUND', '文件夹不存在', false, { id }); if (store.knowledgeFolders.some((item) => item.parentId === id) || store.knowledgeFiles.some((file) => file.folderId === id)) return jsonError(request, 409, 'FOLDER_NOT_EMPTY', '文件夹仍包含子文件夹或文件', false, { id }); store.knowledgeFolders.splice(store.knowledgeFolders.indexOf(folder), 1); return jsonSuccess(request, { id, deleted: true }) }
