import { NextRequest } from 'next/server'
import { jsonError, jsonStoredSuccess, jsonSuccess, successBody } from '@/lib/api/response'
import { getMockStore, getMutation, mutationKey, saveMutation } from '@/lib/mock-store'
import { createRawApiKey, hashApiKey, publicApiKey } from '@/lib/knowledge-security'
import { mutationMeta, parseObject, requiredString, requireSpace } from '@/lib/knowledge-api'
import type { ApiKey, ApiKeyRecord, ApiKeyScope } from '@/lib/types/knowledge'
export const dynamic = 'force-dynamic'
const scopes: ApiKeyScope[] = ['save_conversation', 'save_error', 'search_knowledge']
export async function GET(request: NextRequest) { const keys = getMockStore().knowledgeApiKeys.map(publicApiKey); return jsonSuccess(request, keys, { total: keys.length }) }
export async function POST(request: NextRequest) { const parsed = await parseObject(request); if (parsed.error) return parsed.error; const body = parsed.value!; const name = requiredString(body, 'name', 100); const requestedScopes = Array.isArray(body.scopes) && body.scopes.every((scope) => typeof scope === 'string' && scopes.includes(scope as ApiKeyScope)) ? body.scopes as ApiKeyScope[] : undefined; const spaceId = typeof body.spaceId === 'string' ? body.spaceId.trim() : undefined; if (!name || !requestedScopes || requestedScopes.length === 0) return jsonError(request, 400, 'INVALID_REQUEST', 'name 和 scopes 为必填项', false); const bad = requireSpace(request, spaceId); if (bad) return bad; const meta = mutationMeta(body); const store = getMockStore(); const key = mutationKey(`knowledge-api-keys:create:${meta.actor}`, meta.clientMutationId); const previous = getMutation(store, key); if (previous) return jsonStoredSuccess(previous.body, previous.status); const raw = createRawApiKey(); const now = new Date().toISOString(); const record: ApiKeyRecord = { id: `key-${crypto.randomUUID()}`, name, key: hashApiKey(raw), keyHash: hashApiKey(raw), keyPrefix: raw.slice(0, 8), scopes: requestedScopes, spaceId, usageCount: 0, createdAt: now }; store.knowledgeApiKeys.push(record); const { keyHash: _keyHash, keyPrefix: _keyPrefix, ...publicFields } = record; const responseData: ApiKey = { ...publicFields, key: raw }; const response = successBody(request, responseData, { status: 201 }); saveMutation(store, key, 201, response); return jsonStoredSuccess(response, 201) }
