import { NextRequest } from 'next/server'
import { jsonError, jsonStoredSuccess, jsonSuccess, successBody } from '@/lib/api/response'
import { getMockStore, getMutation, mutationKey, saveMutation } from '@/lib/mock-store'
import { errorSignature, mutationMeta, paginationParams, paginated, parseObject, requiredString, optionalString, requireSpace, spaceMismatch } from '@/lib/knowledge-api'
import { ErrorSeverity, ErrorStatus, type ErrorEntry } from '@/lib/types/knowledge'
export const dynamic = 'force-dynamic'
const severityOrder: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 }
export async function GET(request: NextRequest) { const params = new URL(request.url).searchParams; const spaceId = params.get('spaceId')?.trim(); const status = params.get('status'); const severity = params.get('severity'); const sort = params.get('sort') ?? 'lastOccurredAt'; const bad = requireSpace(request, spaceId); if (bad) return bad; if (status && !Object.values(ErrorStatus).includes(status as ErrorStatus)) return jsonError(request, 400, 'INVALID_QUERY', 'status 不是有效值', false); if (severity && !Object.values(ErrorSeverity).includes(severity as ErrorSeverity)) return jsonError(request, 400, 'INVALID_QUERY', 'severity 不是有效值', false); if (sort !== 'severity' && sort !== 'lastOccurredAt') return jsonError(request, 400, 'INVALID_QUERY', 'sort 不是有效值', false); const pagination = paginationParams(request); if ('error' in pagination) return pagination.error
  const errors = getMockStore().knowledgeErrors.filter((entry) => (!spaceId || entry.spaceId === spaceId) && (!status || entry.status === status) && (!severity || entry.severity === severity)).sort((a, b) => sort === 'severity' ? severityOrder[a.severity] - severityOrder[b.severity] : b.lastOccurredAt.localeCompare(a.lastOccurredAt)); return jsonSuccess(request, paginated(errors, pagination.page, pagination.limit)) }
export async function POST(request: NextRequest) { const parsed = await parseObject(request); if (parsed.error) return parsed.error; const body = parsed.value!; const spaceId = requiredString(body, 'spaceId', 100); const title = requiredString(body, 'title', 200); const errorMessage = requiredString(body, 'errorMessage', 10000); const reproductionPath = requiredString(body, 'reproductionPath', 10000); const severity = body.severity ?? ErrorSeverity.MEDIUM; if (!spaceId || !title || !errorMessage || !reproductionPath || !Object.values(ErrorSeverity).includes(severity as ErrorSeverity)) return jsonError(request, 400, 'INVALID_REQUEST', '错题字段无效', false); const badSpace = requireSpace(request, spaceId); if (badSpace) return badSpace; const meta = mutationMeta(body); const store = getMockStore(); const key = mutationKey(`knowledge-errors:create:${spaceId}:${meta.actor}`, meta.clientMutationId); const previous = getMutation(store, key); if (previous) return jsonStoredSuccess(previous.body, previous.status); const now = new Date().toISOString(); const signature = errorSignature(errorMessage); const existing = store.knowledgeErrors.find((entry) => entry.spaceId === spaceId && entry.signature === signature); if (existing) { existing.occurrenceCount += 1; existing.lastOccurredAt = now; existing.contexts.push({ message: errorMessage, reproductionPath, context: optionalString(body, 'context', 10000), occurredAt: now }); const response = successBody(request, existing); saveMutation(store, key, 200, response); return jsonStoredSuccess(response, 200) } const entry: ErrorEntry = { id: `kerr-${crypto.randomUUID()}`, spaceId, title, errorMessage, signature, severity: severity as ErrorSeverity, reproductionPath, solution: optionalString(body, 'solution', 10000), status: (body.status as ErrorStatus | undefined) ?? ErrorStatus.UNRESOLVED, occurrenceCount: 1, contexts: [{ message: errorMessage, reproductionPath, context: optionalString(body, 'context', 10000), occurredAt: now }], relatedConversationId: optionalString(body, 'relatedConversationId', 100), relatedFileIds: Array.isArray(body.relatedFileIds) ? body.relatedFileIds.filter((id): id is string => typeof id === 'string') : [], firstOccurredAt: now, lastOccurredAt: now }; if (!Object.values(ErrorStatus).includes(entry.status)) return jsonError(request, 400, 'INVALID_REQUEST', 'status 不是有效值', false); store.knowledgeErrors.push(entry); const response = successBody(request, entry, { status: 201 }); saveMutation(store, key, 201, response); return jsonStoredSuccess(response, 201) }
